#!/usr/bin/python3
import os
import shutil
import sys
import compileall as Compiler

from os import listdir
from os.path import isfile, join

def boolquestion(question, default="yes"):
    """Ask a yes/no question via input() and return their answer.

    "question" is a string that is presented to the user.
    "default" is the presumed answer if the user just hits <Enter>.
        It must be "yes" (the default), "no" or None (meaning
        an answer is required of the user).

    The "answer" return value is True for "yes" or False for "no".
    """
    valid = {"yes": True, "y": True, "ye": True,
             "no": False, "n": False}
    if default is None:
        prompt = " [y/n] "
    elif default == "yes":
        prompt = " [Y/n] "
    elif default == "no":
        prompt = " [y/N] "
    else:
        raise ValueError("invalid default answer: '%s'" % default)

    while True:
        sys.stdout.write(question + prompt)
        choice = input().lower()
        if default is not None and choice == '':
            return valid[default]
        elif choice in valid:
            return valid[choice]
        else:
            sys.stdout.write("Please respond with 'yes' or 'no' "
                             "(or 'y' or 'n').\n")

print("Compiling...")
Compiler.compile_dir("src/")

print("./bin Check...")
if os.path.exists("bin"):
	shutil.rmtree("bin")
os.makedirs("bin")
os.makedirs("bin/modules")

print("Moving compiled files...")
cachepath = "src/__pycache__"
files = [f for f in listdir(cachepath) if isfile(join(cachepath, f))]
for file in files:
	shutil.move(join(cachepath, file), "bin/{}.pyc".format(file.split(".")[0]))

cachepath = "src/modules/__pycache__"
files = [f for f in listdir(cachepath) if isfile(join(cachepath, f))]
for file in files:
	shutil.move(join(cachepath, file), "bin/modules/{}.pyc".format(file.split(".")[0]))

print("Renaming gadis-server.pyc...")
os.rename("bin/gadis-server.pyc", "bin/gadis-server")

print("Renaming gadis-remote.pyc...")
os.rename("bin/gadis-remote.pyc", "bin/gadis-remote")

print("Cleaning up...")
shutil.rmtree("src/__pycache__")
shutil.rmtree("src/modules/__pycache__")

install = boolquestion("Install it now?")
if install:
	if os.path.exists("/usr/local/share/gadis"): shutil.rmtree("/usr/local/share/gadis")
	os.makedirs("/usr/local/share/gadis")
	shutil.move("bin/modules", "/usr/local/share/gadis/modules")
	if os.path.exists("/usr/local/sbin/gadis"): os.remove("/usr/local/sbin/gadis")
	if os.path.exists("/usr/local/bin/gadis-server"): os.remove("/usr/local/bin/gadis-server")
	if os.path.exists("/usr/local/bin/gadis-remote"): os.remove("/usr/local/bin/gadis-remote")
	shutil.move("bin/gadis-server", "/usr/local/bin/")
	os.chmod("/usr/local/bin/gadis-server", 0o755)
	shutil.move("bin/gadis-remote", "/usr/local/bin/")
	os.chmod("/usr/local/bin/gadis-remote", 0o755)
	shutil.copy("src/gadis", "/usr/local/sbin/gadis")
	os.chmod("/usr/local/sbin/gadis", 0o755)
	files = [f for f in listdir("bin") if isfile(join("bin", f))]
	for file in files:
		shutil.move(join("bin", file), join("/usr/local/share/gadis", file))
