class Settings():
	Positions = 17
	MaxApplications = 10
	HoursForAdmin = 168
	RemoteHost = "127.0.0.1"
	RemotePort = 9525
	MySQL = {}
	MySQL["Host"] = "127.0.0.1"
	MySQL["Port"] = 3335
	MySQL["Data"] = "bkcservices"
	MySQL["User"] = "bkcservices"
	MySQL["Pass"] = "KguKchYSKsh87J5s87"
	RCON = {}
	RCON["Host"] = "gmod.zenforic.com"
	RCON["Port"] = 27015
	RCON["Pass"] = "anamous12"
	RankName = {}
	RankName[1]  = "Anyone"
	RankName[2]  = "Operator or higher"
	RankName[3]  = "Donator or higher"
	RankName[4]  = "Veteran or higher"
	RankName[5]  = "Veteran or higher"
	RankName[6]  = "Veteran or higher"
	RankName[7]  = "Admin or higher"
	RankName[8]  = "Manager or higher"
	RankName[9]  = "Developer or higher"
	RankName[10] = "Azicus"
	MaxInfractions = {}
	MaxInfractions[1]  = 5
	MaxInfractions[2]  = 5
	MaxInfractions[3]  = 5
	MaxInfractions[4]  = 5
	MaxInfractions[5]  = 5
	MaxInfractions[6]  = 5
	MaxInfractions[7]  = 2
	MaxInfractions[8]  = 2
	MaxInfractions[9]  = 9999
	MaxInfractions[10] = 9999
	cancer_channels = ("cancer")
