#!/bin/bash
help()
{
	echo "USAGE: gadisdev CMD [args]                    "
	echo "                                              "
	echo "Available Commands:                           "
	echo "publish,pub       Publish committed changes   "
	echo "refresh-src,rsrc  Pull changes from remote    "
	echo "view,v            View Gadis console          "
	echo "edit,e            Edit source file in src tree"
}
cmd=$1
shift
case $cmd in
	publish|pub)
		branch="bot-server"
		if [ -n "$1" ]
		then
			branch="$1"
		fi
		cd /root/gadis/working
		git checkout $branch || exit 1
		git fetch --all || exit 1
		git push origin $branch || exit 1
		read -n 1 -p "Run update? [Yn]" ans && echo
		if [ "$ans" != "n" ]
		then
			cd ..
			git clone https://github.com/buildkillchill/gadis-module-discord.git compile
			cp settings/settings.py compile/src/settings.py
			cd compile
			./recompile
			cd ..
			rm -fr compile
		fi
	;;
	refresh-src|rsrc)
		branch="bot-server"
		if [ -n "$1" ]
		then
			branch="$1"
		fi
		cd /root/gadis/working
		git checkout $branch || exit 1
		git fetch --all || exit 1
		git pull origin $branch || exit 1
	;;
	view|v)
		screen -r Gadis
	;;
	edit|e)
		cd /root/gadis/working/src
		mapfile -t files < <(find ./ -iname "$1")
		num=${#files[@]}
		file=""
		if [ $num -eq 0 ]
		then
			echo -e "\e[0;31mSource file not found\e[0m"
			exit 1
		elif [ $num -eq 1 ]
		then
			file="${files[0]}"
		elif [ $num -gt 1 ]
		then
			echo -e "\e[0;31mMore than one source file matching that name was found."
			echo -e "\e[0;32mPossible matches:\e[0;33m"
			for i in ${!files[@]}
			do
				echo -e "  $i) ${files[$i]}"
			done
			echo -e "  \e[0;31m99) None, just exit\e[0m"
			while [ "$file" == "" ]
			do
				read -p "Which file do you want to edit? " f
				if [ "$f" == "99" ]
				then
					echo -e "\e[0;32mOK, bye.\e[0m"
					exit 0
				fi
				file=${files[$f]}
				if [ ! -f "$file" ]
				then
					echo -e "\e[0;31mBad option. Please retry.\e[0m"
					file=""
				fi
			done
		fi
		nano $file
		read -n 1 -p "Make a commit? [yN] " ans && echo
		if [ "$ans" == "y" ]
		then
			read -p "Message: " msg
			git add $file || exit 1
			git commit -m "$msg" || exit 1
			read -n 1 -p "Publish? [Yn] " ans && echo
			if [ "$ans" != "n" ]
			then
				git push origin bot-server
			fi
			read -n 1 -p "Run update? [Yn]" ans && echo
			if [ "$ans" != "n" ]
			then
				cd ..
				git clone https://github.com/buildkillchill/gadis-module-discord.git compile
				cp settings/settings.py compile/src/settings.py
				cd compile
				./recompile
				cd ..
				rm -fr compile
			fi
		fi
	;;
	-h|--help|help|h)
		help
		exit 0
	;;
	*)
		echo "Invalid command"
		help
		exit 1
	;;
esac
