#!/bin/bash
start()
{
	echo -en "\e[0;32mStarting Gadis... "
	if test -n "`screen -ls|grep Gadis`"
	then
		bracket "\e[0;33mRUNNING"
		exit 1
	else
		screen -dmS Gadis /usr/local/bin/gadis
		if test -n "`screen -ls|grep Gadis`"
		then
			bracket "\e[0;32mSUCCESS"
			exit 0
		else
			bracket "\e[0;31mFAILED"
			exit 2
		fi
	fi
}
stop()
{
	echo -en "\e[0;32mGracefully \e[0;33mStopping Gadis... "
	if test -n "`screen -ls|grep Gadis`"
	then
		gadis-remote shutdown
		sleep 0.2
		if test -n "`screen -ls|grep Gadis`"
		then
			bracket " \e[0;31mFAILED"
		else
			bracket "\e[0;32mDONE"
		fi
	else
		bracket "\e[0;33mSTOPPED"
	fi
}
bracket()
{
	echo -e "\e[0;34m[$1\e[0;34m]\e[0m"
}
cmd=$1
shift
case $cmd in
	update|upd)
		cd /root/gadis
		if [ -e compile ]
		then
			rm -fr compile
		fi
		git clone https://github.com/zenforic/Gadis compile
		cp settings/settings.py compile/src/settings.py
		cd compile
		./recompile
		cd ..
		rm -fr compile
	;;
	view|v)
		screen -r Gadis
	;;
	start|run)
		start
	;;
	stop)
		stop
	;;
	force-stop|fstop)
		echo -e "\e[0;31mRudely\e[0m \e[0;33mStopping Gadis...\e[0m"
		pkill -9 gadis-server
	;;
	restart|rstart)
		stop
		sleep 0.2
		if test -n "`screen -ls|grep Gadis`"
		then
			echo -en "\e[0;31mGadis is not stopping, using force stop... "
			pkill -9 gadis-server
			bracket "\e[0;32mDONE"
		fi
		start
	;;
	status)
		echo -en "\e[0;33mGadis is "
		if test -n "`screen -ls|grep Gadis`"
		then
			echo -e "\e[0;32mRunning\e[0m."
			exit 0
		else
			echo -e "\e[0;31mNOT Running\e[0m."
			exit 0
		fi
	;;
esac
