#!/bin/bash
start()
{
	echo -en "\e[0;32mStarting Gadis... "
	if test -n "`screen -ls|grep Gadis`"
	then
		bracket "\e[0;33mRUNNING"
		exit 1
	else
		screen -dmS Gadis /usr/local/bin/gadis
		if test -n "`screen -ls|grep Gadis`"
		then
			bracket "\e[0;32mSUCCESS"
			exit 0
		else
			bracket "\e[0;31mFAILED"
			exit 2
		fi
	fi
}
stop()
{
	echo -en "\e[0;32mGracefully \e[0;33mStopping Gadis... "
	if test -n "`screen -ls|grep Gadis`"
	then
		gadis-remote shutdown
		sleep 0.2
		if test -n "`screen -ls|grep Gadis`"
		then
			bracket " \e[0;31mFAILED"
		else
			bracket "\e[0;32mDONE"
		fi
	else
		bracket "\e[0;33mSTOPPED"
	fi
}
bracket()
{
	echo -e "\e[0;34m[$1\e[0;34m]\e[0m"
}
help()
{
	echo "USAGE: gadisctl CMD [args]                      "
	echo "                                                "
	echo "Available Commands:                             "
	echo "update,upd        Update Gadis from repository  "
	echo "view,v            View Gadis console            "
	echo "start,run         Start Gadis                   "
	echo "stop              Stop Gadis                    "
	echo "force-stop,fstop  Forcefully stop Gadis         "
	echo "restart,rstart    Restart Gadis                 "
	echo "status            Check whether Gadis is running"
}
cmd=$1
shift
case $cmd in
	update|upd)
		if [ -e gadis-compile ]
		then
			rm -fr gadis-compile
		fi
		git clone https://github.com/buildkillchill/gadis-module-discord.git gadis-compile
		cp $1 gadis-compile/src/settings.py
		cd gadis-compile
		./recompile
		cd ..
		rm -fr compile
	;;
	view|v)
		screen -r Gadis
	;;
	start|run)
		start
	;;
	stop)
		stop
	;;
	force-stop|kill)
		echo -e "\e[0;31mRudely\e[0m \e[0;33mStopping Gadis...\e[0m"
		pkill -9 gadis-server
	;;
	restart|rstart)
		stop
		sleep 0.2
		if test -n "`screen -ls|grep Gadis`"
		then
			echo -en "\e[0;31mGadis is not stopping, using force stop... "
			pkill -9 gadis-server
			bracket "\e[0;32mDONE"
		fi
		start
	;;
	status)
		echo -en "\e[0;33mGadis is "
		if test -n "`screen -ls|grep Gadis`"
		then
			echo -e "\e[0;32mRunning\e[0m."
			exit 0
		else
			echo -e "\e[0;31mNOT Running\e[0m."
			exit 0
		fi
	;;
	-h|--help|help|h)
		help
		exit 0
	;;
	*)
		echo "Invalid command"
		help
		exit 1
	;;
esac
