#!/bin/bash
start()
{
	echo -en "\e[0;32mStarting Gadis... "
	if test -n "`screen -ls|grep Gadis`"
	then
		bracket "\e[0;33mRUNNING"
		exit 1
	else
		screen -dmS Gadis /usr/local/bin/gadis
		if test -n "`screen -ls|grep Gadis`"
		then
			bracket "\e[0;32mSUCCESS"
			exit 0
		else
			bracket "\e[0;31mFAILED"
			exit 2
		fi
	fi
}
stop()
{
	echo -en "\e[0;32mGracefully \e[0;33mStopping Gadis... "
	if test -n "`screen -ls|grep Gadis`"
	then
		gadis-remote shutdown
		sleep 0.2
		if test -n "`screen -ls|grep Gadis`"
		then
			bracket " \e[0;31mFAILED"
		else
			bracket "\e[0;32mDONE"
		fi
	else
		bracket "\e[0;33mSTOPPED"
	fi
}
bracket()
{
	echo -e "\e[0;34m[$1\e[0;34m]\e[0m"
}
cmd=$1
shift
case $cmd in
	publish|pub)
		branch="bot-server"
		if [ -n "$1" ]
		then
			branch="$1"
		fi
		cd /root/gadis/working
		git checkout $branch || exit 1
		git fetch --all || exit 1
		git push origin $branch || exit 1
		read -n 1 -p "Run update? [Yn]" ans && echo
		if [ "$ans" != "n" ]
		then
			cd ..
			git clone https://github.com/zenforic/Gadis compile
			cp settings/settings.py compile/src/settings.py
			cd compile
			./recompile
			cd ..
			rm -fr compile
		fi
	;;
	refresh-src|rsrc)
		branch="bot-server"
		if [ -n "$1" ]
		then
			branch="$1"
		fi
		cd /root/gadis/working
		git checkout $branch || exit 1
		git fetch --all || exit 1
		git pull origin $branch || exit 1
	;;
	view|v)
		screen -r Gadis
	;;
	edit|e)
		cd /root/gadis/working/src
		mapfile -t files < <(find ./ -iname "$1")
		num=${#files[@]}
		file=""
		if [ $num -eq 0 ]
		then
			echo -e "\e[0;31mSource file not found\e[0m"
			exit 1
		elif [ $num -eq 1 ]
		then
			file="${files[0]}"
		elif [ $num -gt 1 ]
		then
			echo -e "\e[0;31mMore than one source file matching that name was found."
			echo -e "\e[0;32mPossible matches:\e[0;33m"
			for i in ${!files[@]}
			do
				echo -e "  $i) ${files[$i]}"
			done
			echo -e "  \e[0;31m99) None, just exit\e[0m"
			while [ "$file" == "" ]
			do
				read -p "Which file do you want to edit? " f
				if [ "$f" == "99" ]
				then
					echo -e "\e[0;32mOK, bye.\e[0m"
					exit 0
				fi
				file=${files[$f]}
				if [ ! -f "$file" ]
				then
					echo -e "\e[0;31mBad option. Please retry.\e[0m"
					file=""
				fi
			done
		fi
		nano $file
		read -n 1 -p "Make a commit? [yN] " ans && echo
		if [ "$ans" == "y" ]
		then
			read -p "Message: " msg
			git add $file || exit 1
			git commit -m "$msg" || exit 1
			read -n 1 -p "Publish? [Yn] " ans && echo
			if [ "$ans" != "n" ]
			then
				git push origin bot-server
			fi
			read -n 1 -p "Run update? [Yn]" ans && echo
			if [ "$ans" != "n" ]
			then
				cd ..
				git clone https://github.com/zenforic/Gadis compile
				cp settings/settings.py compile/src/settings.py
				cd compile
				./recompile
				cd ..
				rm -fr compile
			fi
		fi
	;;
esac
